server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: authentification
          uri: lb://authentification
          predicates:
          - Path=/authentification/**
        - id: schedule-service
          uri: lb://schedule-service
          predicates:
            - Path=/schedule/**
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/driver/**
        - id: vehicle-service
          uri: lb://vehicle-service.yml
          predicates:
            - Path=/vehicle/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"